AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
  - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
  - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Lint/UnusedMethodArgument:
  Exclude:
    - 'lambda_function.rb'
